### ISSUE TITLE
The template doesn't show up in Android Studio 3

### ISSUE THREAD

**Issue by hacker1024** [DVDAndroid/XposedModuleTemplate#1]

**Comment by DVDAndroid** [comment]
It works with no problems here. Android Studio 3.0.1, Windows 10.0.16299.125
Could you explain me better?

**Comment by hacker1024** [comment]
There's no **File > New > Other**. I'm on Android Studio Preview Canary 6.

**Comment by mammuth** [comment]
Can confirm this on Android Studio 3.2.1 on macOS.

**Comment by DVDAndroid** [comment]
@mammuth Same Android Studio version, Windows 10
Cannot reproduce this bug

I'll search online if other people with macOS have similar problems

**Comment by DVDAndroid** [comment]
@mammuth 
Do you use this path for macOS?

`/Applications/Android Studio.app/Contents/plugins/android/lib/templates/other/`

**Comment by mammuth** [comment]
Yes. I tried adding the module from an old project, where `File > New > Other` simply wasn't displayed. 

When I created a new dummy project, the menu somehow appeared and the Xposed Module template is showing up ...

**Comment by DVDAndroid** [comment]
Is bug fixed for you?

**Comment by mammuth** [comment]
Yes. It's no bug, rather unexpected behaviour, that the menu item doesn't show up always.
