### ISSUE TITLE
gradle.build file should have compileOnly instead of implemetation

### ISSUE THREAD

**Issue by ViRb3** [DVDAndroid/XposedModuleTemplate#2]
Related line in template:

https://github.com/DVDAndroid/XposedModuleTemplate/blob/fc21073164a91d9527e7f261c40fd46b46949c3d/XposedModule/recipe.xml.ftl#L4

This results in `implements 'de.robv.android.xposed:api:82'`, should be `compileOnly`

**Comment by DVDAndroid** [comment]
I know that it should be `compileOnly`, but there's not API to set it to `compileOnly`; need to be changed manually

**Comment by ViRb3** [comment]
Could you add a note to README.md, this is bound to cause some headaches for Xposed first-timers (like myself).
